version: '3.1'

services:

  postgresdb:
    image: postgres:12.3
    restart: always
    volumes: 
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/logs:/logs
        - ./postgres/config/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: helloworld1!
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports: 
        - 5431:5432