version: '3.1'

services:

  postgresdb:
    image: postgres:12.3
    restart: always
    volumes: 
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/logs:/logs
        - ./postgres/config/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_USER: <your_user>
      POSTGRES_DB: test
    ports: 
        - 5432:5432
